# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET publish

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install wasm-tools
      run: dotnet workload install wasm-tools
    - name: Add build info
      run: ./add_buildinfo.sh
      shell: bash
    - name: Publish release
      run: dotnet publish -c Release
    - name: Remove .wasm files
      run: rm bin/Release/net8.0/publish/wwwroot/_framework/*.wasm
    - name: Remove .gz files
      run: rm bin/Release/net8.0/publish/wwwroot/_framework/*.gz
    - name: Upload to pages
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}
        command: pages publish bin/Release/net8.0/publish/wwwroot --project-name=am5-smu-checker-blazor
    
