# This workflow will publish a .NET Blazor project and deploy it to CloudFlare

name: .NET publish

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Install wasm-tools
      run: dotnet workload install wasm-tools
    - name: Add build info
      run: ./add_buildinfo.sh
      shell: bash
    - name: Publish release
      run: dotnet publish -c Release
    - name: Remove .wasm files
      run: rm bin/Release/net9.0/publish/wwwroot/_framework/*.wasm
    - name: Remove .gz files
      run: rm bin/Release/net9.0/publish/wwwroot/_framework/*.gz
    - name: Upload to pages
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}
        command: pages publish bin/Release/net9.0/publish/wwwroot --project-name=am5-smu-checker-blazor
    
